import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.css';
import Navbar from './components/Navbar/Navbar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Elahly Hospital',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        

      <body className={inter.className}>  <Navbar/>{children}

      
      </body>
    </html>
  )
}
